package org.gro.connectionpool;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class HSQLSetup {

	public static void main(final String[] args) throws SQLException {
		Connection conn = null;
		Statement st = null;
		String sql = null;
		ResultSet rst1 = null;

		try {
			Class.forName("org.hsqldb.jdbcDriver");
		} catch (final Exception ex) {
			ex.printStackTrace();
		}

		conn = DriverManager.getConnection("jdbc:hsqldb:file:/home/mhoms/usuarios", null, null);
		conn.setAutoCommit(true);

		try {
			st = conn.createStatement();
			st.executeUpdate("DROP TABLE ARTIFACTS");
			sql = "CREATE TABLE ARTIFACTS (" +
//        				"ID INTEGER PRIMARY KEY, " +
						"ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, " +
        				"GROUPID VARCHAR(100), " +
        				"ARTIFACTID VARCHAR(100), " +
        				"VERSION VARCHAR(100), " +
        				"JARNAME VARCHAR(100), " +
        				"URL VARCHAR(100), " +
        				"DEPT INTEGER" +
        			")";
			st.executeUpdate(sql);

			st.executeUpdate("DROP TABLE PERSON");
			st.executeUpdate("CREATE TABLE PERSON (" +
					"ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, " +
    				"NAME VARCHAR(100), " +
					"AGE INTEGER" +
				")");


		} catch (final Exception ex) {
			ex.printStackTrace();
		}

		st.executeUpdate("DELETE FROM ARTIFACTS");

		st.executeUpdate("INSERT INTO ARTIFACTS (GROUPID,ARTIFACTID,VERSION,JARNAME,URL,DEPT) VALUES ('jou','jou','2.5.1','javassist-2.5.1.jar','http://repo1.maven.org/maven2/jboss/javassist/2.5.1/',3);");
		st.executeUpdate("INSERT INTO ARTIFACTS (GROUPID,ARTIFACTID,VERSION,JARNAME,URL,DEPT) VALUES ('jou','jou','2.5.1','javassist-2.5.1.jar','http://repo1.maven.org/maven2/jboss/javassist/2.5.1/',3);");
		st.executeUpdate("INSERT INTO ARTIFACTS (GROUPID,ARTIFACTID,VERSION,JARNAME,URL,DEPT) VALUES ('jou','jou','2.5.1','javassist-2.5.1.jar','http://repo1.maven.org/maven2/jboss/javassist/2.5.1/',3);");

		st.executeUpdate("INSERT INTO ARTIFACTS (ID,GROUPID,ARTIFACTID,VERSION,JARNAME,URL,DEPT) VALUES (0,'jboss','javassist','2.5.1','javassist-2.5.1.jar','http://repo1.maven.org/maven2/jboss/javassist/2.5.1/',3);");
		st.executeUpdate("INSERT INTO ARTIFACTS (ID,GROUPID,ARTIFACTID,VERSION,JARNAME,URL,DEPT) VALUES (1,'jboss','javassist','2.6','javassist-2.6.jar','http://repo1.maven.org/maven2/jboss/javassist/2.6/',3);");
		st.executeUpdate("INSERT INTO ARTIFACTS (ID,GROUPID,ARTIFACTID,VERSION,JARNAME,URL,DEPT) VALUES (2,'jboss','javassist','3.0','javassist-3.0.jar','http://repo1.maven.org/maven2/jboss/javassist/3.0/',3);");
		st.executeUpdate("INSERT INTO ARTIFACTS (ID,GROUPID,ARTIFACTID,VERSION,JARNAME,URL,DEPT) VALUES (3,'jboss','javassist','3.0-rc-1','javassist-3.0-rc-1.jar','http://repo1.maven.org/maven2/jboss/javassist/3.0-rc-1/',3);");
		st.executeUpdate("INSERT INTO ARTIFACTS (ID,GROUPID,ARTIFACTID,VERSION,JARNAME,URL,DEPT) VALUES (4,'jboss','javassist','3.1','javassist-3.1.jar','http://repo1.maven.org/maven2/jboss/javassist/3.1/',3);");

//		st.executeUpdate("UPDATE empleados SET departamento='Contabilidad' WHERE codEmpleado=100002");

//		rst1 = st.executeQuery("SELECT * FROM ARTIFACTS WHERE JARNAME LIKE '%1%'");
		rst1 = st.executeQuery("SELECT * FROM ARTIFACTS");
		while (rst1.next()) {
			System.out.println(rst1.getString("ID"));
		}

		rst1.close();
		st = conn.createStatement();
		st.executeUpdate("SHUTDOWN");
		st.close();
		conn.close();
	}

}